services:
  novo-backend:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - NOCODB_BASE_URL
      - NOCODB_API_TOKEN
      - OPENAI_API_KEY
      - ANTHROPIC_API_KEY
    networks:
      - novotalento_default

networks:
  novotalento_default:
    external: true
